### ISSUE TITLE
Travis CI integration and automated releases

### ISSUE THREAD

**Issue by thomastrapp** [html-extract/hext-emscripten#3]
I am going to add automated Travis CI builds and automated releases, that are uploaded to Github when a tag was created.

**Comment by thomastrapp** [comment]
Done!

To trigger a new release, create a new tag, e.g.
```
git tag v0.1.3
git push origin master --tags
```

Travis CI will then build `hext-emscripten`, create a new draft release, and append the files `hext-emscripten.html`, `hext-emscripten.js` and `hext-emscripten.wasm`.

**Comment by brandonrobertz** [comment]
sounds good thanks!
