### ISSUE TITLE
abortOnCannotGrowMemory on large hext extraction

### ISSUE THREAD

**Issue by brandonrobertz** [html-extract/hext-emscripten#4]
Using latest hext-emscripten, I'm getting a `abortOnCannotGrowMemory` exception when loading a large HTML document.

We ought to be able to fix this by setting a compile time flag for emscripten `ALLOW_MEMORY_GROWTH=1`

Reference: https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth

**Comment by brandonrobertz** [comment]
Well, I didn't realize my original branch `brandonrobertz/hext-emscripten` actually silently redirects here, so I pushed the build flag to `master` here. I've tested it and it resolves the issue, but if there are problems we can revert.

**Comment by thomastrapp** [comment]
Thank you for taking care of this!

You can also trigger a new release if you want:
https://github.com/html-extract/hext-emscripten/issues/3#issuecomment-514266274

**Comment by brandonrobertz** [comment]
sounds good thanks! i'll do a new release a bit later

**Comment by brandonrobertz** [comment]
okay this is officially v0.1.5

thanks for setting all this up, it's awesome!
