### ISSUE TITLE
Update to hext v1.0.1

### ISSUE THREAD

**Issue by thomastrapp** [html-extract/hext-emscripten#5]
* update to hext v1.0.1
* update boost
* move from travis to github actions

**Comment by brandonrobertz** [comment]
This is a WIP in https://github.com/html-extract/hext-emscripten/tree/v1.0.0 ... I wanted to turn this all into a GH action, but I need to test across a few different platforms first.

**Comment by thomastrapp** [comment]
Awesome!

https://github.com/html-extract/hext-emscripten/blob/428893d81077bc07414fae808961d00933f96b8b/Makefile.boost#L28-L38
Boost.regex can be used as a "header only library" in boost v1.78. Installing only the headers should therefore work as well.

I'm going to add some commits of my own, specifically the `max_searches` parameter for `Rule::extract` in the wrapper -- Let me know if I should get out of your way or move to another branch.

**Comment by brandonrobertz** [comment]
> 
> Boost.regex can be used as a "header only library" in boost v1.78. Installing only the headers should therefore work as well.
> 
> I'm going to add some commits of my own, specifically the `max_searches` parameter for `Rule::extract` in the wrapper -- Let me know if I should get out of your way or move to another branch.

Go ahead and make whatever changes. I'm running down a compilation problem on the emscripten version that ships with ubuntu 20.04. I think upgrading to 1.78.0 would be smart because I bet some of this is fixed upstream by now (there's even work toward built-in emscripten/"web" target support).

**Comment by thomastrapp** [comment]
I'm done with my changes:
226607f readme: remove travis ci badge
355524f readme: remove python2.7 from build dependencies
3119568 github-actions: upload hext-emscripten.{html,js,wasm} after build
a5a94d4 chmod +x scripts/github-actions/build.sh
0cbcbd0 switch from travis ci to github actions
044b593 remove .travis.yml
b675711 add parameter max_searches for Rule::extract
756b64b update to boost v1.78.0
fd5eda7 test: do not depend on specific version of hext
0a916f3 update to libhext v1.0.1

Github actions builds a release on every push and pull request. Then uploads the build as an artifact, for example:
https://github.com/html-extract/hext-emscripten/actions/runs/1603913225

If these changes look good to you, we can merge this branch to master and create a new tag and release.

**Comment by brandonrobertz** [comment]
Thanks for your commits. I went a step further and completely stopped building the libboost regex library. All we need are the includes, now. The only big code modification I needed to do was in libhext cmake configs, removing the hard checks for regex library, which I accomplished with a patch:

https://github.com/html-extract/hext-emscripten/blob/v1.0.0/libhext-regex-headeronly.patch

LMK if you have any objections to this, but it greatly simplifies the build. I'm going to get the GH actions working now if you weren't already doing that. Everything looks great with hext v1.0!

**Comment by brandonrobertz** [comment]
Okay, very sorry for all the noise with the releases, but now we have automatic release building for version-tagged commits. We could probably consolidate this into a single job, perhaps doing a release conditional to a successful build with a version tag. We could move this into a new issue ticket, though. I think we're all good with v1.0.1!

**Comment by thomastrapp** [comment]
> libhext-regex-headeronly.patch

That's absolutely fine, imho.
(The patch is needed because Boost.regex' cmake configuration files are not getting installed - Without them `find_dependency(Boost COMPONENTS regex)` fails to detect the regex headers as the actual library. Unfortunately, Boost does not have an option to install only the header files and the cmake config).

Thank you for working on this!
