### ISSUE TITLE
Single file hext.js, modularize

### ISSUE THREAD

**Issue by thomastrapp** [html-extract/hext-emscripten#6]
I would like to make the following breaking changes.

@brandonrobertz Let me know if you have any objections.

* build a single file: hext.js (`-s SINGLE_FILE=1`).
* build a loadable module (`-s MODULARIZE=1`, `-s EXPORT_NAME="loadHext"`)
  ```html
  <!-- Use hext.js in a browser -->
  <script src=".../hext.js"></script>
  <script>
    loadHext().then(hext => {
      const rule = new hext.Rule('<a href:x />');
      const html = new hext.Html('<a href="asd"></a>');
      console.log(rule.extract(html));
    });
  </script>
  ```
  ```javascript
  // Use hext.js in node
  var loadHext = require('./hext.js');
  loadHext().then(hext => {
    const rule = new hext.Rule('<a href:x />');
    const html = new hext.Html('<a href="asd"></a>');
    console.log(rule.extract(html));
  });
  ```
* rename repo to html-extract/hext.js
* update readme

**Comment by brandonrobertz** [comment]
Yeah this all looks good to me! My only real wish is that we can continue to use this repo as a CDN (meaning we have the compiled `hext.js` checked in as well as having the release assets available). Everything else can change IMO. The current `Module` use via vanilla emscripten is pretty clunky.

**Comment by thomastrapp** [comment]
(The build will produce a single file, called "hext.js". There will not be a "hext.wasm" or "hext.html" - Let me know if you think we should also publish the ".wasm" or ".html")

> My only real wish is that we can continue to use this repo as a CDN (meaning we have the compiled hext.js checked in as well as having the release assets available)

I think this would be nice:
* [.github/workflows/build.yml](https://github.com/html-extract/hext-emscripten/blob/37cf74607d19244c6b8e5b3eab6d2a447e69a028/.github/workflows/build.yml): Add step that automatically commits the hext.js to the repository on every push, as "dist/hext.js" (using [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) or [EndBug/add-and-commit](https://github.com/EndBug/add-and-commit)). I am using the "dist" subdirectory here, because many JavaScript projects seem to do this by convention.
* The [release.yml](https://github.com/html-extract/hext-emscripten/blob/37cf74607d19244c6b8e5b3eab6d2a447e69a028/.github/workflows/release.yml) workflow can remain unchanged. When a tag is created, the dist/hext.js is already up to date. We can remove the build step and just add the "dist/hext.js" as a release asset. Caveat: If we push a tag before the workflow run of a prior commit has completed, the "dist/hext.js" is possibly out of date. But I don't think that's going to happen.

The CDN url will look like this: `https://cdn.jsdelivr.net/gh/html-extract/hext.js@v1.0.2/dist/hext.js`

I will implement this in a [fork](https://github.com/thomastrapp/hext-emscripten) and see how it goes.

> The current Module use via vanilla emscripten is pretty clunky

Very clunky indeed :)
Using a promise to load hext is an improvement, but ideally, `hext.Rule` and `hext.Html` would just magically appear in the global scope before the DOM ready event. But I couldn't get that to work, because the wasm is parsed/loaded asynchronously.

**Comment by thomastrapp** [comment]
It works well in my fork: https://github.com/thomastrapp/hext-emscripten
The CDN url: https://cdn.jsdelivr.net/gh/thomastrapp/hext-emscripten@v1.0.3/dist/hext.js
Browser tests: https://hext.thomastrapp.com/hext.js-test/  (all OK in Firefox and Android Browser)

I will make the following changes:
* new hext release v1.0.2 (https://github.com/html-extract/hext/compare/v1.0.1...c9be568)
* push my changes to hext-emscripten
* rename repo to html-extract/hext.js
* update hext.js to use new hext release
* update hext.js readme
* new hext.js release
* add documentation for hext.js here: https://hext.thomastrapp.com/download

**Comment by brandonrobertz** [comment]
Awesome! Yes as soon as I checked `hext-emscripten.js/wasm` back into the repo I thought I should have done it via a GH action so I'm glad you did that. And putting it in `dist/` makes the most sense. Green light from me to do all the listed changes. ✅

**Comment by thomastrapp** [comment]
I had another stab at loading hext.js without needing to resolve a promise.

I am documenting this here for future benefit.

There's a relatively new feature: [top-level await in modules](https://v8.dev/features/top-level-await).
The [proposal for top-level await](https://github.com/tc39/proposal-top-level-await) specifically mentions its usefulness to modules using WebAssembly.

Replace the export code in hext.js (last ~6 lines of code) with the following:
```js
const hextInternal = await loadHext(); // works only in ES6 modules
const hext = {
  Rule: hextInternal.Rule,
  Html: hextInternal.Html,
};
export { hext as default, hext, loadHext };
```

And then you can use it like this:
```html
<script type="module">
  import { hext } from '..../hext.js';
  const rule = new hext.Rule("asd");
  // ...
</script>
```

I am pretty sure that there is another way. A possible avenue is using webpack and the wasm output from emscripten.

**Comment by brandonrobertz** [comment]
Yeah so if you want to go the module route, which I think is smart, we could boil it down to this if we exported Rule and Html (right now loadHext is the only export AFAICT):

```
import { Rule, Html } from 'https://cdn.jsdelivr.net/gh/thomastrapp/hext-emscripten@v1.0.3/dist/hext.js';
```


This would be by far the simplest way to accomplish the loading. But of course it will make it so old browsers can't work with it. I don't think that should restrain us, though. We're pretty much the only hext.js users right now and we should be looking forward. $0.02.

**Comment by brandonrobertz** [comment]
All right so I've done a bit of poking around and almost got to the above. 

If we use the `-s EXPORT_ES6=1` flag in our `Makefile` then we can load hext with a single script (two lines of JS using one await):

```
    <script type="module">
      import loadHext from "/hext.js";
      const { Rule, Html } = await loadHext();
    </script>
```

In order to get to the single line `import {Rule, Html} from '/hext.js'` import, we'll need to mess with the [pre/post-js args to the closure compiler](https://emscripten.org/docs/tools_reference/emcc.html?highlight=modularize#emcc-post-js). I can keep going down this path, but wanted to hear your thoughts.

**Comment by brandonrobertz** [comment]
Okay, so I went down the rabbit hole and got a fully loaded `hext.js` module that lets us do this in the browser:

```html
<script type="module">
  import { Rule, Html } from "https://cdn.jsdelivr.net/gh/html-extract/hext-emscripten@hext.js/hext.js";
  const html = new Html("<ul><li>Hello</li><li>World</li></ul>");
  const rule = new Rule("<li @text:my_text />");
  const result = rule.extract(html).map(x => x.my_text).join(", ");
  console.log(result); // "Hello, World"
</script>
```

The module also lets you import `hext` like:

```javascript
import hext from "/hext.js";
// ... use hext.Html, hext.Rule ...
```

I created a new branch with this work: [hext.js](https://github.com/html-extract/hext-emscripten/tree/hext.js) The next thing I want to look at is reducing the size of the JS/WASM bundle and fixing the broken tests/node.js usage.

Let me know what you think and thanks for getting this kicked off!

**Comment by thomastrapp** [comment]
Just to clarify, I wished I could use hext.js like this:
```html
<script src=".../hext.js"></script> // no module
<script>
  console.log(new hext.Rule("<a/>")); // No call to loadHext required
</script>
```

And I don't want to force users to use modules.
But I haven't found a solution yet. So I have to be content with loadHext for now (It is also not that important, but I love to brood over details like this).

How about this:
* dist/hext.js -> non-module, with loadHext
* dist/hext.mjs -> module, without loadHext (like in your branch)

Is that a good solution?


I am currently improving the documentation at https://hext.thomastrapp.com/download whenever I find the time.
Let me know if you want to release this as soon as possible. I will then prioritize the new release.

Off-topic: I really like your example
```
// <ul><li>Hello</li><li>World</li></ul>
// <li @text:my_text />
const result = rule.extract(html).map(x => x.my_text).join(", ");
console.log(result); // "Hello, World"
```

That's beautiful.

**Comment by brandonrobertz** [comment]
> Just to clarify, I wished I could use hext.js like this:
> ```html
> <script src=".../hext.js"></script> // no module
> <script>
>   console.log(new hext.Rule("<a/>")); // No call to loadHext required
> </script>
> ```

Makes sense. Using WASM is going to prevent that as the API is async. One option (not sure if this can work) would be to use emscripten's non-WASM build (pure JS) but I think we would need to heavily modify the loader JS.

> How about this:
> * dist/hext.js -> non-module, with loadHext
> * dist/hext.mjs -> module, without loadHext (like in your branch)
> 
> Is that a good solution?

Perfect solution. I didn't realize node.js hated the ES6 module, so it's best to keep it in the .mjs file.


> Off-topic: I really like your example
> ```
> // <ul><li>Hello</li><li>World</li></ul>
> // <li @text:my_text />
> const result = rule.extract(html).map(x => x.my_text).join(", ");
> console.log(result); // "Hello, World"
> ```
> 
> That's beautiful.
 
😂 Thanks

**Comment by thomastrapp** [comment]
https://cdn.jsdelivr.net/gh/html-extract/hext.js/dist/hext.js
https://cdn.jsdelivr.net/gh/html-extract/hext.js/dist/hext.mjs

All done - Thanks!
